In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Tensors
***Definition**:* A tensor is a specialized multi-dimensional array designed for mathematical and computational efficiency.

Dimension: The number of directions in which a tensor spans.

These are the types of tensors based on dimensions:
- Scalar (0-dimensional tensor): Represents a single value often used for simple values or constants. Example: 7, 8.5, 3.14
- Vector (1-dimensional tensor): Represents a sequence or collection of values. Example: [0, 2, 5], word embeddings vector
- Matrix (2-dimensional tensor): Represents tabular or grid-like data (collection of vectors). Example [[0, 3, 2],[6, 7, 5]], grayscale image (each cell represents pixel intensity from 0 to 255)
- 3D tensors (3-dimensional tensor): Often used for stacking data. Example: Coloured images (RGB images) (width * height * channels)
- 4D tensors (4-dimensional tensors): Batches of RGB images. Example: (#images * width * height * channels)
- 5D tensors (5-dimensional tensors): Video data. Dataset of video clips where each clip is made of certain number of frames and each frame is an RGB image.

## Why are tensors useful?
- **Mathematical Operations**: Tensors enable easy and efficient mathematical computations such as addition, dot product and so on.
- **Representation of Real world data**: We can easily and intuitively represent real world data using tensors.
- **Efficient computations**: Tensors are constructed in such a way that we can use hardware such as GPUs and TPUs to perform highly intensive computations in an efficient manner. This becomes crucial in training deep learning models.

## Installation and set up

In [2]:
!pip3 install torch torchvision

In [3]:
import torch
print(torch.__version__)

2.4.0


In [4]:
if torch.cuda.is_available():
    print("GPU is available.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available, using CPU instead.")

GPU is available.
Using GPU: Tesla T4


## Creating a tensor

In [5]:
# using empty
# empty() function allocates memory space according to size specified and just returns whatever data is already stored in that memory space.
a = torch.empty((2, 3))
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# check type
type(a) # returns torch.Tensor

torch.Tensor

In [7]:
# using zeroes
zero_tensor = torch.zeros((3, 4))
print(f"zero_tensor: {zero_tensor}")

# using ones
one_tensor = torch.ones((2, 5, 4))
print(f"one_tensor: {one_tensor}")

zero_tensor: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
one_tensor: tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [8]:
# using rand
rand_tensor = torch.rand((3, 5))
print(rand_tensor)

# However, using rand() would allocate values to the tensor at random. To get some sort of deterministic reproduceability, we can use `seed` with rand()
torch.manual_seed(100)
manual_seed_rand_tensor = torch.rand((3, 5)) # this would create the same random tensor with the manual seed every time it is executed.
print(manual_seed_rand_tensor)

tensor([[0.7353, 0.2866, 0.2491, 0.9187, 0.3981],
        [0.5035, 0.0384, 0.1635, 0.0869, 0.8526],
        [0.7768, 0.7328, 0.7027, 0.8809, 0.4050]])
tensor([[0.1117, 0.8158, 0.2626, 0.4839, 0.6765],
        [0.7539, 0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876, 0.4183]])


In [9]:
# using tensor
torch.tensor([1.3, 2.66, 4.7])

tensor([1.3000, 2.6600, 4.7000])

In [10]:
# other ways

print(f"using arange -> {torch.arange(0, 10, 3)}")

print(f"using linspace -> {torch.linspace(0, 10, 12)}")

print(f"using identity matrix -> {torch.eye(5)}")

print(f"using full -> {torch.full((4, 3), 9)}")

using arange -> tensor([0, 3, 6, 9])
using linspace -> tensor([ 0.0000,  0.9091,  1.8182,  2.7273,  3.6364,  4.5455,  5.4545,  6.3636,
         7.2727,  8.1818,  9.0909, 10.0000])
using identity matrix -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])


## Tensor shapes

In [11]:
x = torch.tensor([[2, 3, 4.5], [3.4, 20, 2]])
print(f"Shape of x: {x.shape}")

Shape of x: torch.Size([2, 3])


In [12]:
torch.empty_like(x) # creates an empty tensor with same shape as x

tensor([[-2.7592e+10,  3.2699e-41, -2.7662e+10],
        [ 3.2699e-41,  1.1210e-43,  0.0000e+00]])

In [13]:
torch.zeros_like(x) # creates a zeros tensor with same shape as x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones_like(x) # creates a ones tensor with same shape as x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.rand_like(x) # creates a rand tensor with same shape as x

tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784]])

## Tensor data types

In [16]:
# use dtype to print the data type of tensor
print(f"Data type of elements in tensor: {x.dtype}")

Data type of elements in tensor: torch.float32


In [17]:
# create a tensor by explicitly specifying the data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
# change the data type of existing tensor by using to() function
x.to(torch.float32)

tensor([[ 2.0000,  3.0000,  4.5000],
        [ 3.4000, 20.0000,  2.0000]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

In [19]:
x = torch.rand((2, 3))
print(f"x = {x}")

x = tensor([[0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445]])


In [20]:
# addition
print(f"add 2 -> {x + 2}")

# subtraction
print(f"sub 2 -> {x - 2}")

# multiplication
print(f"add 2 -> {x * 2}")

# division
print(f"add 2 -> {x / 2}")

# integer division
print(f"add 2 -> {(x * 100) // 2}")

# modulus
print(f"mod 3 -> {((x * 100) // 2) % 3}")

# power
print(f"power 4 -> {x ** 4}")

add 2 -> tensor([[2.8238, 2.5557, 2.9770],
        [2.4440, 2.9478, 2.7445]])
sub 2 -> tensor([[-1.1762, -1.4443, -1.0230],
        [-1.5560, -1.0522, -1.2555]])
add 2 -> tensor([[1.6477, 1.1115, 1.9540],
        [0.8880, 1.8957, 1.4890]])
add 2 -> tensor([[0.4119, 0.2779, 0.4885],
        [0.2220, 0.4739, 0.3722]])
add 2 -> tensor([[41., 27., 48.],
        [22., 47., 37.]])
mod 3 -> tensor([[2., 0., 0.],
        [1., 2., 1.]])
power 4 -> tensor([[0.4607, 0.0954, 0.9112],
        [0.0389, 0.8071, 0.3072]])


## Elementwise operations

In [21]:
a, b = torch.rand((3, 4)), torch.rand((3, 4))

# addition
print(f"a + b -> {a + b}")

# subtraction
print(f"a - b -> {a - b}")

# multiplication
print(f"a * b -> {a * b}")

# division
print(f"a / b -> {a / b}")

a + b -> tensor([[1.3794, 0.7588, 0.7362, 1.1753],
        [0.5902, 1.1091, 0.9496, 0.0616],
        [0.7332, 1.8586, 1.3053, 0.6079]])
a - b -> tensor([[-0.4010, -0.2737,  0.6645, -0.1199],
        [-0.0958,  0.4726, -0.1026, -0.0278],
        [-0.2915,  0.0485,  0.1075, -0.2821]])
a * b -> tensor([[4.3549e-01, 1.2523e-01, 2.5131e-02, 3.4175e-01],
        [8.4790e-02, 2.5169e-01, 2.2279e-01, 7.5470e-04],
        [1.1317e-01, 8.6302e-01, 4.2303e-01, 7.2481e-02]])
a / b -> tensor([[ 0.5495,  0.4698, 19.5165,  0.8148],
        [ 0.7206,  2.4852,  0.8050,  0.3784],
        [ 0.4311,  1.0535,  1.1796,  0.3660]])


In [22]:
c = torch.tensor([[1, 2.3, -2.45], [-4.66, -9.02, -11]])

In [23]:
# absolute value of tensor
print(f"Absolute value of c: {torch.abs(c)}")

# negative value of every element
print(f"Negative c: {torch.neg(c)}")

# Round
print(f"Round c: {torch.round(c)}")

# Ceil
print(f"Ceil c: {torch.ceil(c)}")

# Floor
print(f"Floor c: {torch.floor(c)}")

# Clamp
# All values <= min become min and all values >=max become max
print(f"Clamp min=2 max=5: {torch.clamp(torch.abs(c), min=2, max=5)}")

Absolute value of c: tensor([[ 1.0000,  2.3000,  2.4500],
        [ 4.6600,  9.0200, 11.0000]])
Negative c: tensor([[-1.0000, -2.3000,  2.4500],
        [ 4.6600,  9.0200, 11.0000]])
Round c: tensor([[  1.,   2.,  -2.],
        [ -5.,  -9., -11.]])
Ceil c: tensor([[  1.,   3.,  -2.],
        [ -4.,  -9., -11.]])
Floor c: tensor([[  1.,   2.,  -3.],
        [ -5., -10., -11.]])
Clamp min=2 max=5: tensor([[2.0000, 2.3000, 2.4500],
        [4.6600, 5.0000, 5.0000]])


## Reduction operations

In [24]:
e = torch.randint(size = (3, 4), low = 0, high = 10, dtype = torch.float32)
e

tensor([[9., 2., 6., 7.],
        [7., 8., 3., 6.],
        [1., 5., 5., 0.]])

In [25]:
# sum
print(f"Sum of all elements: {torch.sum(e)}")

# sum along columns
print(f"Sum along columns: {torch.sum(e, dim = 0)}")

# sum along rows
print(f"Sum along rows: {torch.sum(e, dim = 1)}")

Sum of all elements: 59.0
Sum along columns: tensor([17., 15., 14., 13.])
Sum along rows: tensor([24., 24., 11.])


In [26]:
# mean
print(f"Mean of all elements: {torch.mean(e)}")

# mean along columns
print(f"Mean along columns: {torch.mean(e, dim=0)}")

# median
print(f"Median of all elements: {torch.median(e)}")

# max and min
print(f"Max of elements along columns: {torch.max(e, dim = 0)}")
print(f"Min of elements along rows: {torch.min(e, dim = 1)}")

# product
print(f"Product of all elements: {torch.prod(e)}")

# standard deviation
print(f"Standard deviation: {torch.std(e)}")

# variance
print(f"Variance: {torch.var(e)}")

# argmax: position of the biggest element in e (when flattened)
# argmin: position of the smallest element in e (when flattened)
print(f"Argmax: {torch.argmax(e)}")
print(f"Argmin: {torch.argmin(e)}")

Mean of all elements: 4.916666507720947
Mean along columns: tensor([5.6667, 5.0000, 4.6667, 4.3333])
Median of all elements: 5.0
Max of elements along columns: torch.return_types.max(
values=tensor([9., 8., 6., 7.]),
indices=tensor([0, 1, 0, 0]))
Min of elements along rows: torch.return_types.min(
values=tensor([2., 3., 0.]),
indices=tensor([1, 2, 3]))
Product of all elements: 0.0
Standard deviation: 2.8431203365325928
Variance: 8.083333015441895
Argmax: 0
Argmin: 11


## Matrix operations

In [27]:
a = torch.randint(size = (2, 4), low = 2, high = 7, dtype=torch.float32)
b = torch.randint(size = (4, 5), low = 3, high = 9, dtype=torch.float32)

In [28]:
# matrix mulitplication
print(f"a matmul b: {torch.matmul(a, b)}")

a matmul b: tensor([[100.,  63., 128., 113., 137.],
        [ 71.,  42.,  83.,  68.,  97.]])


In [29]:
c, d = torch.tensor([1, 2]), torch.tensor([3, 4])
# dot product
print(f"c dot d: {torch.dot(c, d)}")

c dot d: 11


In [30]:
# transpose
print(f"transpose of a: {torch.transpose(a, 0, 0)}")

transpose of a: tensor([[6., 5., 5., 5.],
        [5., 5., 2., 2.]])


In [31]:
sq = torch.randint(size = (4, 4), low = 3, high = 12, dtype = torch.float32)
# determinant
print(f"Determinant of sq: {torch.det(sq)}")

# inverse
print(f"Inverse of sq: {torch.inverse(sq)}")

Determinant of sq: -818.0003662109375
Inverse of sq: tensor([[-0.0049, -0.0746, -0.1834,  0.3337],
        [-0.1051,  0.1467,  0.5575, -0.5746],
        [ 0.2738, -0.3240, -0.7311,  0.8105],
        [-0.0367,  0.1907,  0.1247, -0.2469]])


## Comparison operations

In [32]:
i = torch.randint(size = (3, 3), low = 0, high = 10)
j = torch.randint(size = (3, 3), low = 0, high = 10)

print(f"i > j: {i > j}")
print(f"i < j: {i > j}")
print(f"i == j: {i > j}")
print(f"i != j: {i > j}")

i > j: tensor([[False, False, False],
        [False, False, False],
        [False,  True,  True]])
i < j: tensor([[False, False, False],
        [False, False, False],
        [False,  True,  True]])
i == j: tensor([[False, False, False],
        [False, False, False],
        [False,  True,  True]])
i != j: tensor([[False, False, False],
        [False, False, False],
        [False,  True,  True]])


## Special functions

In [33]:
k = torch.randint(size = (2, 3), low = -10, high = 10, dtype = torch.float32)
k

tensor([[ 9.,  2.,  7.],
        [ 0., -8.,  4.]])

In [34]:
# log
print(f"log: {torch.log(k)}")

# exp
print(f"log: {torch.exp(k)}")

# sqrt
print(f"sqrt: {torch.sqrt(k)}")

# sigmoid
print(f"sigmoid: {torch.sigmoid(k)}")

# softmax
print(f"softmax: {torch.softmax(k, dim = 0)}")

# relu
print(f"relu: {torch.relu(k)}")

log: tensor([[2.1972, 0.6931, 1.9459],
        [  -inf,    nan, 1.3863]])
log: tensor([[8.1031e+03, 7.3891e+00, 1.0966e+03],
        [1.0000e+00, 3.3546e-04, 5.4598e+01]])
sqrt: tensor([[3.0000, 1.4142, 2.6458],
        [0.0000,    nan, 2.0000]])
sigmoid: tensor([[9.9988e-01, 8.8080e-01, 9.9909e-01],
        [5.0000e-01, 3.3535e-04, 9.8201e-01]])
softmax: tensor([[9.9988e-01, 9.9995e-01, 9.5257e-01],
        [1.2339e-04, 4.5398e-05, 4.7426e-02]])
relu: tensor([[9., 2., 7.],
        [0., 0., 4.]])


## Inplace operations

In [35]:
# for larger datasets we do not want to create a new tensor everytime we perform some operations
# we can perform inplace operations as well
m = torch.rand((2, 3))
n = torch.rand((2, 3))

m.add_(n)

tensor([[0.9331, 0.5003, 1.4965],
        [1.1200, 1.9371, 1.0893]])

In [36]:
m

tensor([[0.9331, 0.5003, 1.4965],
        [1.1200, 1.9371, 1.0893]])

In [37]:
m.relu_()

tensor([[0.9331, 0.5003, 1.4965],
        [1.1200, 1.9371, 1.0893]])

In [38]:
m

tensor([[0.9331, 0.5003, 1.4965],
        [1.1200, 1.9371, 1.0893]])

## Copying a tensor

In [39]:
a = torch.rand((3, 4))
b = a
a[0][0] = 0.34
print(a[0][0] == b[0][0])

b = a.clone()

a[0][0] = 0.12
print(a[0][0] == b[0][0])

tensor(True)
tensor(False)


## Tensor operations on GPU

In [40]:
device = torch.device('cuda')
device

device(type='cuda')

In [41]:
gpu_tensor = torch.rand((3, 5), device=device)
gpu_tensor

tensor([[0.3563, 0.0303, 0.7088, 0.2009, 0.0224],
        [0.9896, 0.3737, 0.0823, 0.2851, 0.4433],
        [0.2989, 0.4175, 0.2687, 0.0927, 0.2317]], device='cuda:0')

In [42]:
# moving tensor to gpu
gpu_x = x.to(device)

In [43]:
import time

size = 10000

a_cpu, b_cpu = torch.rand((size, size)), torch.rand((size, size))
start_time_cpu = time.time()
result_cpu = torch.matmul(a_cpu, b_cpu)
end_time_cpu = time.time()

print(f"CPU matrix multiplication time: {end_time_cpu - start_time_cpu}")

a_gpu, b_gpu = torch.rand((size, size), device=device), torch.rand((size, size), device=device)
start_time_gpu = time.time()
result_gpu = torch.matmul(a_gpu, b_gpu)
torch.cuda.synchronize()
end_time_gpu = time.time()

print(f"GPU matrix multiplication time: {end_time_gpu - start_time_gpu}")

CPU matrix multiplication time: 7.335745096206665
GPU matrix multiplication time: 0.6826832294464111
